controller:
  adminUsername: admin
  adminPassword: admin

  ingress:
    enabled: true
    hostName: "jenkins.yourcluster.com"
  JCasC:
    defaultConfig: true
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: Welcome to Kube-Jenkins!