apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: jenkins
    namespace: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: efs-sc
  resources:
    requests:
      storage: 8Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: jenkins